eclipse-tinydtls/tinydtls

dtls.c, dtls_debug.c, dtls_debug.h, sha2/sha2.c
dtls.c:
Add in const for dtls_handshake_type_to_name()
dtls_debug.[ch]:
Add in const where appropriate for dsrv_log().
In addition, get dsrv_log() to check printf syntax.
sha2/sha2.c:
Re-order "const static" to "static const" and add in needed const.
=> Use of -Wwrite-strings and -Wextra throw up compiler warnings

tests/dtls-client.c, tests/dtls-server.c
tests/dtls-client.c:
tests/dtls-server.c:
Correct parameters when calling dtls_debug() or dtls_warn().
=> Correct printf formatting errors when using dsrv_log()

platform-specific/dtls_prng_espidf.c
platform-specific/dtls_prng_espidf.c:
Add in #include <esp_system.h>
=> Include missing file in platform-specific/dtls_prng_espidf.c

aes/rijndael.c
aes/rijndael.c:
Change #define ESPIDF_VERSION to DTLS_EXT_RIJNDAEL
=> Make compilation of aes/rijndael.c more generic for external rijndaelEncrypt

dtls.c
Reporting a diagnostic message of ALRT for a normal close notify
(when a DTLS session is closed down) is confusing.
dtls.c:
Change the logging level to INFO if it is a Close Notify alert.
=> dtls_alert() is called when receiving a Close Notify

dtls.c, dtls_mutex.h
When there is a limited stack size, having the send buffer (which everything
is built into prior to sending) on the stack can easily cause stack overflows.
dtls_mutex.h:
Create dtls_ mutex functions which are platform independent.
dtls.c:
Move sendbuf out of the functions' stack and make it a static variable
if DTLS_CONSTRAINED_STACK is defined.
Protect the usage of sendbuf by mutexes.
=> When working with limited stacks, having sendbuf on the stack can cause issues

dtls.c
Update to "#ifdef DTLS_CONSTRAINED_STACK"
=> "#if DTLS_CONSTRAINED_STACK" fails with esp-idf compiler

dtls.c
Seen in the client when using using tinydtls client and tinydtls server 
with a mismatch of PSK keys. See PR #8 comments for example of valgrind output.
dtls.c:
Clear out the on stack buf variable to zero in dtls_send_client_key_exchange() 
before adding in encrypted data (which could be rounded up to a block size) 
later on in the function.
Example valgrind output
==8967== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
==8967==    at 0x5121AB2: send (in /lib64/libc-2.12.so)
==8967==    by 0x407863: coap_network_send (coap_io.c:767)
==8967==    by 0x4093AE: coap_socket_send (coap_io.c:1424)
==8967==    by 0x409FBE: coap_session_send (coap_session.c:229)
==8967==    by 0x40CAE0: dtls_send_to_peer (coap_tinydtls.c:105)
==8967==    by 0x4202AF: dtls_send_multi (in …
=> dtls_send_client_key_exchange does not preset all bytes before being sent out

sha2/sha2.c, sha2/sha2.h
dtls_sha256_transform() fails for esp-idf systems as the data parameter
is a uint32 and may not be aligned aligned to a word boundary when
processing the server-hello handshake.
sha2/sha2.c:
Make the data parameter byte aligned (as does most other sha256
implementations) for function dtls_sha256_transform().
=> sha2.c: Fix for systems that do not support non word alignment

hmac.h
For ESP-IDF, use the ESP-IDF sha356 hash implementation to save on code
size.
=> hmac.h: Add in ESP-IDF sha256 versions

.gitignore, Makefile.in, Makefile.tinydtls, aes/Makefile.in, aes/Makefile.riot, aes/rijndael.c, aes/rijndael.h, aes/rijndael_wrap.c
Some platforms already provide the primary rijndael functions, but do not
have the specific TinyDTLS wrapper functions.
This change is to split out the primary (i.e. common) rijndael functions
(leave in rijndael.c) and the TinyDTLS wrapper functions (put into
rijndael_wrap.c) and removing the appropriate #ifdef DTLS_EXT_RIJNDAEL.
.gitignore:
Ignore .so library file
Makefile.in:
Makefile.tinydtls:
aes/Makefile.in:
aes/Makefile.riot:
Add in rijndael_wrap.[co] as appropriate.
aes/rijndael.c:
Remove the wrapper functions.
aes/rijndael_wrap.c: (New)
Add in the wrapper functions.
=> Separate out rijndael.c into primary and wrapper functions

global.h
This PR fixes the behavior of a server in RIOT built with only PSK support when an ECC client sends a second ClientHello to it.
The server does not return `handshake_failure` as described in the [4th paragraph Section 7.4.1.2 of TLS 1.2 RFC](https://tools.ietf.org/html/rfc5246#section-7.4.1.2) because receiving buffer has a size of `DTLS_MAX_BUF` which is too small to receive a ClientHello from an ECC client.
A step-by-step guide reproducing this issue on RIOT is described in RIOT-OS/RIOT#12351. I tested by applying this patch after commit dcac93 which is the current version used in RIOT.
I cannot test this with the latest develop because there is error when using latest commit on develop on RIOT but I don't think it is related to this PR.
=> Set bigger DTLS_MAX_BUF for Contiki/RIOT

dtls_time.h
when compiling RIOT on FreeBSD with TinyDTLS package it fails because the CLOCK_SECOND macro is already defined. This adds an `#undef` right before it redefinition to fix that.
=> dtls_time.h: fix CLOCK_SECOND redefined on FreeBSD

dtls.h
This allows RAM to be freed up.
Signed-off-by: Jon Shallow supjps-libcoap@jpshallow.com
=> dtls.h: Remove readbuf from dtls_context_t as it is unused

crypto.c
Fix L sizes broken by cbe1810f8c123b1b458dbb7f06acb5e02414edf3 reworking.
=> crypto.c: Fix L used for nonce sizes

Makefile.in, configure.ac
Allow the user to disable shared library through --disable-shared.
Indeed, building of shared libraries is not supported by all toolchains
especially embedded ones
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
=> add --disable-shared option

sha2/sha2.c
Build is broken since 865ec9ba1d44e629c1107c299aebd20e901a19ff because tmp is undefined in put32be and put64be:
```
/home/buildroot/autobuild/instance-1/output-1/host/bin/m68k-linux-gcc -DSHA2_USE_INTTYPES_H -Wall -std=c99 -pedantic -fPIC -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DDTLSv12 -DWITH_SHA256 -I..  -c -o sha2.o sha2.c
sha2.c: In function 'get32be':
sha2.c:164:2: warning: implicit declaration of function 'MEMCPY_BCOPY' [-Wimplicit-function-declaration]
MEMCPY_BCOPY(&tmp, data, sizeof(tmp));
^~~~~~~~~~~~
sha2.c: In function 'put32be':
sha2.c:177:34: error: 'tmp' undeclared (first use in this function)
MEMCPY_BCOPY(data, &val, sizeof(tmp));
^~~
```
Fix this error by replacing tmp by val
Moreover, move MEMCPY_BCOPY before its usage or linking step will fail …
=> sha2/sha2.c: fix build on big endian

dtls.c
As per #32 DTLS_CE_LENGTH evaluates to 97, but only 94 bytes are needed.
Remove DTLS_CE_LENGTH and define output buffer size for 
dtls_send_certificate_ecdsa() for clarity to be
uint8 buf[sizeof(uint24) + DTLS_EC_SUBJECTPUBLICKEY_SIZE];
=> dtls.c: Fix size of buffer for dtls_send_certificate_ecdsa()

dtls.c
The renegotiate Client Hello had the record layer set to DTLS 1.0 when
it should have been DTLS 1.2.
Only when epoch == 0 set it to DTLS 1.0.
This fix does not include support for RFC5746 Renegotiation Indication
Extension
This fixes #23 
=> dtls.c: Fix renegotiate

platform-specific/dtls_prng_riot.c
Use the system-provided [PRNG](http://doc.riot-os.org/group__sys__random.html) instead relying on `rand()` from libc.
same as #15, but for RIOT
Signed-off-by: Benjamin Valentin <benjamin.valentin@ml-pa.com>
=> dtls_prng_riot: use random_bytes()

README, configure.ac
configure.ac:
Remove spurious ] from the CUNIT test
README:
Include autoreconf to handle configure.ac updates.
=> configure.ac: Fix CUNIT spurious bracket

dtls.c
Move extended_master_secret addition in dtls_send_client_hello() out of ecdsa addition check so that it is always sent.
Fix for #50
=> ExtendedMasterSecret: Support sending it for PSK

dtls.c
Fix variable usage when dtls_get_cookie() fails.
=> dtls.c: Bad return value in dtls_verify_peer()

dtls.c
Until feature/handshake_fragmentation is merged, reject any fragmented
handshake otherwise fragmented handshakes may cause a DoS.
Addresses issue raised in #59.
=> dtls.c: Reject any fragmented handshake until fragmentation supported

dtls.c
If insufficient data, alert out.
=> dtls.c: Validate cookie length in check_server_hello_verify_request()

crypto.c, crypto.h, dtls.c
In ASN.1, these are positive signed integer values, big-endian encoded.
There is an additional 0x00 prefix if the number has the signed bit set, so
that the number remains positive - hence length can be > 32.
If the leading bits are 0, and there is more than 8 of them, then the leading
0x00 byte(s) can be dropped - hence length can be < 32.
This fix allows the dtls_check_ecdsa_signature_elem() to work correctly.
=> sha256: Handle r and s values that do not use 32 bytes

tests/dtls-client.c, tests/dtls-server.c
tests/dtls-client.c:
Fix ALERT generated when communicating with an IPv4 host.
tests/dtls-server.c:
Support binding to an IPv4 address.
=> tests: Handle IPv4/IPv6 selection better

dtls.c
RFC 5246 7.2 Alert Protocol
Alert messages
with a level of fatal result in the immediate termination of the
connection.
=> dtls.c: Destroy peer on generation of fatal alert during handshake

dtls.c
Fix code updated by #87 to check for peer != NULL.
=> dtls.c: Fix check for peer

dtls.c
=> Use DTLS_ALERT_DECRYPT_ERROR on verify_data mismatch in a FINISH

dtls.c, peer.h
The PR is on the top of some other pending ones.
If at all merged, it is intended to be merged after these PRs.
Use the record and message sequence numbers of that client_hellos for
either sending a hello verify request or starting the handshake on the
server side with sending a server_hello.
The function of a HELLO_REQUEST is unclear and therefore not considered.
In some scopes a HELLO_REQUEST is only used for associated peers to
trigger a rehandshake (handshake executed within an previous encrypted
association, epoch > 0), and some scopes seems to handle also
situations, where either no previous association is required or the new
handshake is executed in epoch 0. That may be clarified either before or
after this change.
=> Add separate stateless processing for client_hello of epoch 0.

dtls.c
Fixes #97 
Fail on odd cipher suite length.
=> Fix issue 97

dtls.c
Add DTLS_ECC macros to include CertificateRequest processing only, if
build supports ECC.
=> Include CertificateRequest only for ECC builds.

dtls.c, dtls.h, peer.h
In general the handshake state machine forces the handshakes to go
through
a defined order. But optional handshake message are not controlled by
that.
This fix introduces a optional handshake message field. With that, the
state-machine is enabled to check, if this message is (optionally)
expected. When processed, the field is reset and receiving the optional
message twice will therefore fail the handshake.
=> dtls.c: Check for optional handshake messages

crypto.h
The implementation allows both, encrypt and decrypt, to use overlapping
src and buf.
Add missing documentation for src to dtls_decrypt_params.
Fixes: Issue #24
=> crypto.h: correct documentation about overlapping of src and buf.

dtls.c
=> dtls.c: Remove unused security variable

dtls.c
Adapt the test of the return value of decrypt_verify
be larger than 0 on all places.
=> dtls.c: use dtls_security_params_read_epoch when decode record.

.gitignore, Makefile.in, configure.ac, tinydtls.pc.in
In some cases it might be advantageous to install tinydtls to some (system-wide) prefix (e.g. `/usr/local`) and use it from there.
Because the tinydtls headers require the header sub-directory (i.e. `/usr/local/include/tinydtls` if the prefix is `/usr/local`) to be in the header search path, software that uses tinydtls has to add `-I[HEADER_PATH]` to its compiler flags (as well as the `-L[LIB_PATH] -ltinydtls` linker flags if the prefix is not part of the standard library search path). 
By providing a pkg-config file, it is possible for build scripts in dependent projects to automatically set the appropiate compiler and linker flags for tinydtls without having to manually find the tinydtls subdirectory in one of its header search path entries.
The format of the pkg-config file follows the …
=> Add support for pkg-config in tinydtls

dtls.c
The last dtls handshake flights are very special on both sides. The
server doesn't retransmit the last flight on it's own. The server only
retransmits the last flight, if the client's last flight is received
again.
Therefore it's important, that the client doesn't stop the
retransmission of the last flight just by receiving the server's
ChangeCipherSpec.
Fix it by moving the dtls_stop_retransmission into the error handling.
=> dtls.c: fix retransmission of last flight.

dtls.c
The received message is cloned in order to store it in the handshake
message queue. If the message is then processed delayed, removing it is
not enough. The node must be freed in order to free the cloned message
as well.
=> dtls.c: fix memory leak in handshake message queue.

dtls_time.h, sha2/sha2speed.c, tests/dsrv-test.c, tests/dtls-client.c, tests/dtls-server.c
Include time.h and sys/time.h based on HAVE_TIME_H and HAVE_SYS_TIME_H.
A first port for zephyr shows, that accidentally included time headers cause some other headers (socket) to fail. Easiest work-around is to switch these includes using the available macros. 
=> dtls_time.h: conditionally include time header files.

crypto.h, dtls.c
Reorder check and reuse record_sequence difference and drop duplicates earlier.
Fixes: Issue #71
=> dtls.c: cleanup record_sequence_filter.

dtls.c, netq.h
Fix waiting without timeout in DTLS_STATE_CLOSING after Alert.
Sending Alert according RFC6347 without retransmission is not reliable.
Therefore a dummy retransmission entry is used for outgoing Alerts. On
retransmission, the Alert is not retransmitted, instead handle_alert is
called to emulate receiving the response.
Issue #95
=> Fix Alert timeout

alert.h, dtls.c
Cleanup peer and send alert back, if processing a address-verified
ClientHello fails.
Fixes wrong content-type in dtls_0_send_alert as well.
=> dtls.c: fix missing alerts when receiving a ClientHello in epoch 0.

session.c, session.h
Using tinydtls on RIOT OS is not limited to GNRC as network stack. It is also working with e.g. lwIP, see: https://github.com/RIOT-OS/RIOT/pull/17552. Therefore the name WITH_RIOT_GNRC is misleading.
PR in RIOT OS has already been approved and was merged: 
- https://github.com/RIOT-OS/RIOT/pull/17765
=> Rename condition WITH_RIOT_GNRC to WITH_RIOT_SOCK

dtls.c, dtls_time.h, netq.c
Uses proposal in issue #125 to fix a 32bit overflow.
Fixes issue: #125
=> dtls.c, netq.c: consider 32bit time overflow.

session.c, session.h
As described in https://github.com/RIOT-OS/RIOT/pull/17849, having `port` and `addr` as separate fields in the `session_t` was causing in certain scenarios to include random bytes (possible due to padding) to the hash calculation for the cookie. This would in turn cause the server to generate inconsistent cookies, thus failing to perform the handshake.
This PR joins the port and the IPv6 address into a single member, which is used to calculate the size.
=> session.h: Modify session_t for RIOT

configure.ac
By setting CFLAGS in configure, commit b9c58a1f [1]
accidentally prevents passing additional CFLAGS
parameters into make.
[1] https://github.com/eclipse/tinydtls/commit/b9c58a1f237599402b1b3ecc339ea49c98de387d
Change-Id: Ibfb0a805e690cf401f77e53c9a58f4e75a668aa8
=> configure.ac: Prevent overwriting CFLAGS in configure

dtls_time.c, dtls_time.h
RIOT is currently migrating from its [xtimer](https://doc.riot-os.org/group__sys__xtimer.html) to [ztimer](https://doc.riot-os.org/group__sys__ztimer.html) high level timer abstraction.
The new API allows better sleep management. `xtimer` was based in microseconds and in this library-port, it was using 64bits. This PR is changing it to use `ztimer_msec`, so milliseconds based. It's also using 32bits timestamps instead of 64bits used by `xtimer`.
Since `contiki` also uses 32bits my assumption is that a 32bit millisecond timer should be enough as a backend for the `dtls_time` api, is there any reason why this assumption would be wrong?
I have provided test results for this in the PR making this change in RIOT-OS/RIOT, (see https://github.com/RIOT-OS/RIOT/pull/17564). In that PR this change …
=> dtls_time: migrate to ztimer_msec

dtls.c
Ignore malformed alerts instead of process them as fatal_alert.
=> dtls.c: consider data_length processing incoming alert.

dtls.c
=> dtls.c: check always  dtls_state for ServerKeyExchange.

session.c, session.h
Add the capability to communicate using IPv4.
PR in RIOT OS has already been approved and was merged: 
- https://github.com/RIOT-OS/RIOT/pull/17765
Dependencies:
- #127
- #128
I'll rebase once the dependencies are merged.
Off-topic:
At first glance the project seemed to be stale, but after looking into the develop branch it became clear it is not. I just wanted to point out that some first-time users (like me) might get the wrong impression when they see that the latest commit to master is from July 2020 ;)
=> Add IPv4 support for RIOT OS

AutoConf.cmake, CMakeLists.txt, dtls_config.h.cmake.in, tests/CMakeLists.txt
Currently tinydtls uses EPL-1.0 and mixing with EPl-2.0 is not
recommended. Therefore adjust the EPL-2.0 of new files to
EPL-1.0.
=> Use EPL-1.0 for recently new files.

crypto.c
The second "if handshake" and "if security" are obsolete.
=> crypto.c: remove obsolete if.

dtls.c
For ASN.1 integers greater than 128 (i.e., with the most significant bit set) the encoded length might exceed *data_len. The length check is done upfront to ensure that the specified number of octets does
not exceed the actual *data_len.
This bug was reported by Shisong Qin.
This PR supersedes PR #152.
=> dtls.c: fix off-by-one error in dtls_asn1_len()

dtls.c
In handle_0_verified_client_hello(), an existing peer is released and replaced by a new peer object. To ensure that references to this peer are cleared, dtls_destroy_peer() must be called with the unlink flag set.
Moreover, when handle_verified_client_hello() fails for the new peer structure, dtls_destroy_peer() must be called for that peer as well to ensure removal from the sendqueue.
This issue has been reported by Shisong Qin, cf. #133
=> dtls.c: Fix incomplete release of peer

session.h
Required for libcoap LwIP builds that need encryption.
=> session.h: Support compiling for LwIP

dtls.c, dtls.h
`dtls.c` already provides a `dtls_send_multi()` function to send data from discontinuous buffers.
Also provide this functionality to the user, so e.g. protocol header and payload data can be supplied in separate buffers, removing the requirement for an additional work buffer on the application side.
=> dtls.c: introduce dtls_writev()

dtls.c, dtls.h
While https://github.com/eclipse/tinydtls/pull/159 made a very useful addition by introducing `dtls_writev`, it made `dtls_write` unusable in shared libraries by turning it into a `static inline` function. This PR proposes reintroducing `dtls_write` as a "regular" function when not building for an RTOS (Contiki, RIOT, or Zephyr), making it available in shared libraries again.
Using a doxygen member group, it should be possible to reuse the documentation for both function variants, reducing redundancy.
=> dtls: redefine `dtls_write` without `static inline`

.github/workflows/main.yml, .gitignore, CMakeLists.txt, README.md, dtls.c, dtls.h, dtls_debug.c, dtls_debug.h, dtls_mutex.h, dtls_prng.c, dtls_time.c, ecc/ecc.c, platform-specific/dtls_prng_win.c, session.h, sha2/sha2.h, tests/dtls-server.c, tinydtls.h
In order to make tinydtls more cross-platform compatible, this PR adds Windows support by conditionally including header files, an additional PRNG implementation, and missing definitions. This way tinydtls can be cross-compiled for Windows using MinGW, for example.
Some workarounds (type definitions in `sha2.h` and alternative included headers in `tests/dtls-server.c`) have been added in order to be able to actually compile the library. Using MinGW, some errors/warnings are thrown because a number of definitions from a libary called `Ws2_32.lib` cannot be found, but the resulting `libtinydtls.so` can be used as a `.dll` file under Windows nonetheless.
By running, for example, `./configure --host x86_64-w64-mingw32` you can generate Makefiles to test the cross-compilation on a Linux …
=> Add Windows support

CMakeLists.txt, zephyr/CMakeLists.txt
Exclude cmake options for zephyr builds, if these are set by zephyr.
=> Fix cmake warnings of zephyr builds.

dtls.c, dtls_debug.c, dtls_prng.c, dtls_time.c, dtls_time.h, platform-specific/dtls_prng_lwip.c, platform-specific/lwip_platform.h, session.c, session.h, tinydtls.h
Follow the model of how things are done for Contiki.
Set up a new WITH_LWIP_NO_SOCKET (which happens with NO_SYS = 1)
and use this when setting up addresses.
Add in platform specific for dtls_prng_lwip.c and lwip_platform.h
Update dtls_time.[ch] to handle LWIP version of time.
Code works for NO_SYS = 1 or NO_SYS = 0.
=> LwIP: Support LwIP builds when NO_SYS = 1

dtls_debug.c, dtls_debug.h
Allow the application to define a log handler callback to use to provide
consistency in the logging output logic.
=> dtls_debug: Add in support for separate logging handler

dtls.c, dtls_debug.c
Found when libcoap LwIP builds removed the -Wno-unused-parameter option.
=> LwIP: Fix unused parameter compiler warnings

platform-specific/dtls_prng_win.c, tinydtls.h
This PR addresses the warning `warning C4013: 'rand_s' undefined; assuming extern returning int` that is currently emitted when compiling with Visual Studio.
See the `Build Windows App` step of [this GitHub Actions job](https://github.com/namib-project/dart_tinydtls_libs/actions/runs/3525588540/jobs/5912489087) for reference.
=> windows: move `_CRT_RAND_S` to `tinydtls.h`

global.h
When bumping `DTLS_MAX_BUF` to encrypt larger messages (e.g. to be sent over Ethernet) the size of the stack-allocated `sendbuf` will also grow.
This can lead to surprising crashes / stack corruption as thread stacks are usually not that large.
To prevent this, automatically enable `DTLS_CONSTRAINED_STACK` if `DTLS_MAX_BUF` is beyond a given threshold (default size with `DTLS_ECC`).
=> global.h: enable constrained stack if DTLS_MAX_BUF is too large

Makefile.riot, dtls_debug.h
tinydtls allows to switch log levels at run-time.
This means that all debug log strings and formaters are included in the binary, which comes at a significant ROM cost.
On RIOT we can define a `tinydtls_debug` pseudo-module that enables the debug facilities, but in it's absence we can just skip building `dtls_debug.c` and turn log functions into no-ops.
We can still make use of RIOT's log facilities, but there the log level is set at build time so the compiler will turn everything below that into a no-op.
=> RIOT: make use of log.h for dsrv_log()

dtls_debug.h
While trying to figure out why tinydtls still requires `gettimeofday()` even though `dtls_ticks()` uses ZTimer now, I found that it's still used via `time()` in `dtls_dsrv_hexdump_log()`.
Replace it with a native hexdump function as it was done for Zephyr.
This allows us to drop the `gettimeofday` compat modules that was so far needed to build tinydtls with RIOT.
``` 
text	   data	    bss	    dec	    hex	filename
123068	    384	  24920	 148372	  24394	/home/benpicco/dev/RIOT/examples/dtls-sock/bin/openmote-b/dtls_sock.elf
```
```
text	   data	    bss	    dec	    hex	filename
107756	    272	  24776	 132804	  206c4	/home/benpicco/dev/RIOT/examples/dtls-sock/bin/openmote-b/dtls_sock.elf
```
=> RIOT: make use od module for hexdump

crypto.h, dtls.c, dtls.h, tests/CMakeLists.txt, tests/Makefile.in, tests/dtls-client.c, tests/dtls-server.c, tests/dtls_ciphers_util.c, tests/dtls_ciphers_util.h
Add callback for peer specific selection of cipher suites.
=> Select cipher suites (2.)

CONTRIBUTING.md
=> Amend source formatting with rule for function definitions with multiple lines

tests/dtls-client.c, tests/dtls-server.c, tests/dtls_ciphers_util.c
Some compilers complain that index is already defined in <strings.h>. Replace index with lindex.
=> tests: Fix compiler clash over index usage in test suites

dtls_debug.c
Setting `NDEBUG` already replaces `dtls_dsrv_hexdump_log()`, `dtls_dsrv_log_addr()` etc with dummy implementations.
This extends this to also replace `dsrv_log()` and `dtls_{get,set}_log_level()` with a no-op implementation.
=> dtls_debug: mock dsrv_log() when NDEBUG is set

tests/Makefile.in, tests/dtls-client.c
As discussed in PR #194 the pre-processor symbol `_GNU_SOURCE` used in the examples` Makefile could be replaced by `_POSIX_C_SOURCE=200112L` to provide the functions `kill()` and `getaddrinfo()`.
The drawback is that `NI_MAXSERV` then needs to be defined manually.
=> Replace pre-processor symbols for gnu source with posix in examples

dtls.c
=> dtls.c: add check for valid handshake message type when version is 1.0.

dtls_debug.c
=> dtls_debug.c: only enable _GNU_SOURCE for MinGW builds.

tests/dtls-client.c
The previous version ignores the option for the local port. That may be
caused by issues using the same default local port for the server and
client.
This enables the use of an specific local port and changes the default
to an ephemeral free port, similar to quite a lot of other UDP clients.
The DEFAULT_PORT is therefore only used for the destination.
=> Apply option local port

CMakeLists.txt
Using the Ninja generator with the MSVC compiler leads to errors due to incorrect compiler call options. In CMake, the generator and the compiler are different entities.
This fix replaces the incorrect CMake variable with the correct one that describes the current MSVC-compatible compiler.
=> Fix MSVC compilation (CMake-based)
