tests/dtls-server.c

dtls-server.c: Trap SIGINT to help with valgrind

---

dtls.c

If insufficient data, alert out.
Fixes #55.

dtls.c: Check length of data for ServerHello

---

dtls.c

Make sure that bitfield is correctly used for tracking missing packets and
that a large block of missing packets do not cause an over shift.
Fixes #57.

dtls.c: Correctly handle missing packets checking

---

dtls.c

Record epoch as well as sequence number.

dtls.c: Update logging for received records

---

dtls.c

Ignore record-MAC violations.

---

dtls.c

Fix some logging statements.
Fix some misleading comments.
Use dtls_decrypt/encrypt with params to prepare for CCM additional to CCM8.

Prepare for ccm

---

dtls.c

Issue #100
Ensure, that at least one cipher suite and one compression method is
present. Add skip for left compression methods.

dtls.c: Fix cipher suite and compression method decoding.

---

dtls.c

Also drop Application Data records of epoch 0.
Fixes: Issue #114

dtls.c: drop Alert and Application Data records in new epochs before processing Finish.

---

dtls_debug.c

Providing a too small buffer may result in missing the zero termination.
This fix prevents that, even if currently no too small buffers are
used.

dtls_debug.c: fix minor bug with zero termination.

---

dtls.c

Improve slightly the logging in dtls_handle_message.

---

AutoConf.cmake
CMakeLists.txt
crypto.c
dtls.c
dtls_config.h.cmake.in
dtls_debug.c
dtls_debug.h
dtls_mutex.h
dtls_prng.c
dtls_time.c
dtls_time.h
netq.c
platform-specific/dtls_prng_zephyr.c
session.h
zephyr/CMakeLists.txt
zephyr/Kconfig

Add initial support for zephyr.

Support zephyr.

---

configure.ac

configure.ac: Fix with test for inet_ntop for building dtls_debug.o

---

.github/workflows/main.yml
Makefile.in
aes/Makefile.in
ecc/Makefile.in
sha2/Makefile.in
tests/Makefile.in
tests/unit-tests/Makefile.in

Unfortunately out of path builds do not work at present.

github: Add in build and test workflow

---

AutoConf.cmake
CMakeLists.txt

cmake: Convert files to unix format from dos format

---

dtls.c
dtls.h
tests/dtls-client.c
tests/dtls-server.c

Remove renegotiation

---

dtls.c

dtls.c: minor cleanup of cookie check.

---

AutoConf.cmake
configure.ac
dtls_config.h.cmake.in
platform-specific/dtls_prng_posix.c

Add #error with explanation and hint to solve it.

dtls_prng_posix.c: fail for posix without HAVE_GETRANDOM.

---

dtls.c

If alerts remove the peer, additional records need to be dropped.

dtls.c: fix processing of alerts.

---

alert.h
dtls.c

Renegotiation has been removed.
Cleanup some leftovers internal renegotiation errors.

dtls.c: remove rudiments of renegotiation.

---

dtls.c

Improve comment on length calculations.

dtls.c: explain calculation for cipher suites (max).

---

crypto.c

crypto.c: Support -O3 compiler builds

---

dtls.c

Do not calculate the cookie using the Extensions as these are different between DTLS1.2 and DTLS1.3
https://datatracker.ietf.org/doc/html/rfc6347#section-4.2.1
When responding to a HelloVerifyRequest, the client MUST use the same parameter values (version, random, session_id, cipher_suites, compression_method) as it did in the original ClientHello.  The server SHOULD use those values to generate its cookie and verify that they are correct upon cookie receipt.
https://www.rfc-editor.org/rfc/rfc9147.html#section-5.3
The ClientHello up to, but not including the Extensions is the same for DTLS1.2 and DTLS1.3
Alternative implementation for PR #223 with boundary checks using SKIP_VAR_FIELD.

dtls.c: exclude Extensions when calculating cookie.

---

dtls.c

Use empty client certificate, if a certificate is requested but no certificate is available.
Issue #186

dtls.c: support empty client certificate.

---

dtls.c

dtls.c: complete verification of length of Alert record.
